In [66]:
sucesion = []
for i in range(36):
    n = i + 1
    sucesion.append(200+(n-1)*24)
    print("Término",n,":",sucesion[i])

Término 1 : 200
Término 2 : 224
Término 3 : 248
Término 4 : 272
Término 5 : 296
Término 6 : 320
Término 7 : 344
Término 8 : 368
Término 9 : 392
Término 10 : 416
Término 11 : 440
Término 12 : 464
Término 13 : 488
Término 14 : 512
Término 15 : 536
Término 16 : 560
Término 17 : 584
Término 18 : 608
Término 19 : 632
Término 20 : 656
Término 21 : 680
Término 22 : 704
Término 23 : 728
Término 24 : 752
Término 25 : 776
Término 26 : 800
Término 27 : 824
Término 28 : 848
Término 29 : 872
Término 30 : 896
Término 31 : 920
Término 32 : 944
Término 33 : 968
Término 34 : 992
Término 35 : 1016
Término 36 : 1040


In [67]:
suma = sum(sucesion)
print("La suma de los primeros términos es",suma)

La suma de los primeros términos es 22320


In [80]:
sucesion = []

# Queremos calcular hasta el mes 9
for i in range(9):
    n = i + 1
    
    # Rellenamos el "Término general" con la fórmula:
    # Capital * (1.012) elevado a la n
    termino = 2000000 * (1.012)**n
    
    sucesion.append(termino)
    
    # Imprimimos con formato de moneda para que se lea mejor (sin decimales largos)
    print("Mes", n, ": $", "{:,.0f}".format(sucesion[i]))


Mes 1 : $ 2,024,000
Mes 2 : $ 2,048,288
Mes 3 : $ 2,072,867
Mes 4 : $ 2,097,742
Mes 5 : $ 2,122,915
Mes 6 : $ 2,148,390
Mes 7 : $ 2,174,170
Mes 8 : $ 2,200,260
Mes 9 : $ 2,226,664


matriz

In [96]:
import numpy as np
A = np.array([[300, 272,240],
              [260, 180,324]])

B = np.array([[1200, 1250],
              [1100, 1400],
               [1350, 1200,]])


#Transpuesta de una matriz
T = B.T

#Multiplicación de matrices
C = A.dot(B)

In [147]:
print(C)

[[ 983200 1043800]
 [ 947400  965800]]


In [100]:
sucesion = []
for i in range(9):
    n = i + 1
    sucesion.append(533*(2**(n-1)))
    print("Término",n,":",sucesion[i])

Término 1 : 533
Término 2 : 1066
Término 3 : 2132
Término 4 : 4264
Término 5 : 8528
Término 6 : 17056
Término 7 : 34112
Término 8 : 68224
Término 9 : 136448


In [101]:
final = 34112
termino = 0
n = 0
dif = final-termino
while dif > 0:
    n += 1
    termino = sucesion[n-1]
    dif = final-termino

if dif==0:
    print("El término",final,"está en la posición",n)
else:
    print("El término",final,"no está en la sucesión")

El término 34112 está en la posición 7


In [143]:
sucesion = []
for i in range(30):
    n = i + 1
    sucesion.append(1000000+(n-1) *36000)
    print("Término",n,":",sucesion[i])

Término 1 : 1000000
Término 2 : 1036000
Término 3 : 1072000
Término 4 : 1108000
Término 5 : 1144000
Término 6 : 1180000
Término 7 : 1216000
Término 8 : 1252000
Término 9 : 1288000
Término 10 : 1324000
Término 11 : 1360000
Término 12 : 1396000
Término 13 : 1432000
Término 14 : 1468000
Término 15 : 1504000
Término 16 : 1540000
Término 17 : 1576000
Término 18 : 1612000
Término 19 : 1648000
Término 20 : 1684000
Término 21 : 1720000
Término 22 : 1756000
Término 23 : 1792000
Término 24 : 1828000
Término 25 : 1864000
Término 26 : 1900000
Término 27 : 1936000
Término 28 : 1972000
Término 29 : 2008000
Término 30 : 2044000


In [144]:
final = 1828000
termino = 0
n = 0
dif = final-termino
while dif > 0:
    n += 1
    termino = sucesion[n-1]
    dif = final-termino

if dif==0:
    print("El término",final,"está en la posición",n)
else:
    print("El término",final,"no está en la sucesión")

El término 1828000 está en la posición 24


In [155]:
#Definición de matrices en Python
A = np.array([[360, 280,150,420],
              [450, 370,210,130],
              [240,260,320,340]])

B = np.array([[130, 310,230,280],
              [270, 240,520,370],
              [190,290,460,410]])


#Transpuesta de una matriz
T = B.T

#Multiplicación de matrices
C = A.dot(B)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [154]:
print(T)

[[130 270 190]
 [310 240 290]
 [230 520 460]
 [280 370 410]]


In [158]:
import numpy as np
A=np.array([[2,3],[1,4]])
b=np.array([[52],[56]])
AI=np.linalg.inv(A)
sol=AI.dot(b)
print(sol)


[[ 8.]
 [12.]]
